In [1]:
a=3

In [2]:
type(a)

int

In [3]:
bList=[2,4,6,8,10]

In [4]:
bList.append(12)

In [5]:
bList

[2, 4, 6, 8, 10, 12]

In [6]:
bList.clear()

In [7]:
bList

[]

In [8]:
bList=[2,3]

In [9]:
cList=bList.copy()

In [10]:
cList

[2, 3]

In [11]:
dList=cList

In [12]:
dList

[2, 3]

In [13]:
bList.count(2)

1

In [14]:
bList.append(2)

In [15]:
bList.count(2)

2

In [16]:
bList=[3,4,10,3,2,12,10]

In [17]:
bList.index(10)

2

In [18]:
bList

[3, 4, 10, 3, 2, 12, 10]

In [19]:
bList.insert(2,15)

In [20]:
bList

[3, 4, 15, 10, 3, 2, 12, 10]

In [21]:
a=bList.pop()

In [22]:
a

10

In [23]:
bList.remove(3)

In [24]:
bList

[4, 15, 10, 3, 2, 12]

In [25]:
bList.remove(3)

In [26]:
bList

[4, 15, 10, 2, 12]

In [27]:
bList.reverse()

In [28]:
bList

[12, 2, 10, 15, 4]

In [29]:
bList.sort(reverse=True)

In [30]:
bList

[15, 12, 10, 4, 2]

In [31]:
dList=[bList,cList]

In [32]:
dList

[[15, 12, 10, 4, 2], [2, 3]]

In [33]:
a=[2,3]

In [34]:
a

[2, 3]

In [35]:
eList=dList.copy()

In [36]:
eList

[[15, 12, 10, 4, 2], [2, 3]]

In [37]:
fList=[dList,eList]

In [38]:
fList

[[[15, 12, 10, 4, 2], [2, 3]], [[15, 12, 10, 4, 2], [2, 3]]]

In [39]:
gList=[fList,fList]

In [40]:
gList

[[[[15, 12, 10, 4, 2], [2, 3]], [[15, 12, 10, 4, 2], [2, 3]]],
 [[[15, 12, 10, 4, 2], [2, 3]], [[15, 12, 10, 4, 2], [2, 3]]]]

In [61]:
eList

[[15, 12, 10, 4, 2], [2, 3]]

In [68]:
eList[1][0:2]

[2, 3]

In [41]:
import numpy
a=numpy.zeros(3)
a

array([0., 0., 0.])

In [88]:
a=numpy.zeros((4,3))

In [89]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
b=numpy.zeros((2,4,3))

In [45]:
b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
c=numpy.ones((3,4))

In [47]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
c=c*6

In [49]:
c

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [50]:
d=numpy.eye(5)

In [51]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
e=d[0:4,0:3]
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [53]:
import numpy as np

In [54]:
a1=np.ones((3,4,2))
a1

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [55]:
a2=a1[0:2,0:2,0:2]

In [56]:
a2

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [57]:
a1[0]

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [92]:
a1[0,0:2,1:2]

array([[1.],
       [1.]])

In [90]:
a1

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])