In [158]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.formula as sm
import statsmodels.api as sm

In [140]:
data=pd.read_csv("multi.csv")
data.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [141]:
real_x=data.iloc[:,0:4].values
real_y=data.iloc[:,4].values

In [142]:
#le=LabelEncoder()
#real_x[:,3]=le.fit_transform(real_x[:,3])
#type(real_x)
#real_x

In [143]:
ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(categories='auto'), [3])], remainder='passthrough')
real_x = ct.fit_transform(real_x)

In [144]:
real_x=real_x[:,1:]


In [145]:
training_x,test_x,training_y,test_y=train_test_split(real_x,real_y,test_size=0.2,random_state=0)

In [146]:
test_x

array([[1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [147]:
MLR=LinearRegression()
MLR.fit(training_x,training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [148]:
pred_y=MLR.predict(test_x)
pred_y

array([103015.20159796, 132582.27760815, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230166,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

In [149]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [150]:
MLR.coef_

array([-9.59284160e+02,  6.99369053e+02,  7.73467193e-01,  3.28845975e-02,
        3.66100259e-02])

In [151]:
MLR.intercept_

42554.16761772438

In [153]:
real_x=np.append(arr=np.ones((50,1)).astype(int),values=real_x,axis=1)
real_x

array([[1, 1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 1, 0.0, 1.0, 9

In [165]:
X_opt = np.array(real_x[:, [0, 1, 2, 3, 4, 5]], dtype=float)
regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()
regressor_OLS

In [166]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     205.0
Date:                Mon, 06 Apr 2020   Prob (F-statistic):           2.90e-28
Time:                        01:17:44   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1064.
Df Residuals:                      45   BIC:                             1073.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        2.73e+04   3185.530      8.571      0.000    2.09e+04    3.37e+04
x1           2.73e+04   3185.530      8.571      0.000    2.09e+04    3.37e+04
x2          1091.1075   3377.087      0.323      0.748   -5710.695    7892.910
x3           -39.3434   3309.047     -0.012      0.991   -6704.106    6625.420
x4             0.8609      0.031     27.665      0.000       0.798       0.924
x5            -0.0527      0.050     -1.045      0.301      -0.154       0.049
==============================================================================
Omnibus:                       14.275   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.260
Skew:                          -0.953   Prob(JB):                     6.57e-05
Kurtosis:                       5.369   Cond. No.                     7.08e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.15e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [168]:
X_opt = np.array(real_x[:, [0, 1, 2, 4, 5]], dtype=float)
regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     279.4
Date:                Mon, 06 Apr 2020   Prob (F-statistic):           1.59e-29
Time:                        01:28:07   Log-Likelihood:                -526.75
No. Observations:                  50   AIC:                             1062.
Df Residuals:                      46   BIC:                             1069.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.729e+04   3060.993      8.917      0.000    2.11e+04    3.35e+04
x1          2.729e+04   3060.993      8.917      0.000    2.11e+04    3.35e+04
x2          1111.1761   2893.049      0.384      0.703   -4712.230    6934.582
x3             0.8609      0.031     28.127      0.000       0.799       0.922
x4            -0.0527      0.050     -1.057      0.296      -0.153       0.048
==============================================================================
Omnibus:                       14.252   Durbin-Watson:                   1.197
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.188
Skew:                          -0.953   Prob(JB):                     6.81e-05
Kurtosis:                       5.362   Cond. No.                     4.50e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.33e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [169]:
X_opt = np.array(real_x[:, [0, 1, 4, 5]], dtype=float)
regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     426.8
Date:                Mon, 06 Apr 2020   Prob (F-statistic):           7.29e-31
Time:                        01:28:22   Log-Likelihood:                -526.83
No. Observations:                  50   AIC:                             1060.
Df Residuals:                      47   BIC:                             1065.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.744e+04   3008.359      9.122      0.000    2.14e+04    3.35e+04
x1          2.744e+04   3008.359      9.122      0.000    2.14e+04    3.35e+04
x2             0.8621      0.030     28.589      0.000       0.801       0.923
x3            -0.0530      0.049     -1.073      0.289      -0.152       0.046
==============================================================================
Omnibus:                       14.678   Durbin-Watson:                   1.189
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               20.449
Skew:                          -0.961   Prob(JB):                     3.63e-05
Kurtosis:                       5.474   Cond. No.                     3.51e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.75e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [170]:
X_opt = np.array(real_x[:, [0, 1, 5]], dtype=float)
regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.040
Model:                            OLS   Adj. R-squared:                  0.020
Method:                 Least Squares   F-statistic:                     2.015
Date:                Mon, 06 Apr 2020   Prob (F-statistic):              0.162
Time:                        01:29:52   Log-Likelihood:                -599.63
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      48   BIC:                             1207.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.849e+04   1.27e+04      3.040      0.004     1.3e+04    6.39e+04
x1          3.849e+04   1.27e+04      3.040      0.004     1.3e+04    6.39e+04
x2             0.2887      0.203      1.419      0.162      -0.120       0.698
==============================================================================
Omnibus:                        0.126   Durbin-Watson:                   0.099
Prob(Omnibus):                  0.939   Jarque-Bera (JB):                0.110
Skew:                           0.093   Prob(JB):                        0.947
Kurtosis:                       2.866   Cond. No.                     8.98e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.61e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [171]:
X_opt = np.array(real_x[:, [0, 1]], dtype=float)
regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()
regressor_OLS.summary()

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Mon, 06 Apr 2020   Prob (F-statistic):                nan
Time:                        01:30:30   Log-Likelihood:                -600.65
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      49   BIC:                             1205.
Df Model:                           0                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.601e+04   2850.077     19.651      0.000    5.03e+04    6.17e+04
x1          5.601e+04   2850.077     19.651      0.000    5.03e+04    6.17e+04
==============================================================================
Omnibus:                        0.018   Durbin-Watson:                   0.020
Prob(Omnibus):                  0.991   Jarque-Bera (JB):                0.068
Skew:                           0.023   Prob(JB):                        0.966
Kurtosis:                       2.825   Cond. No.                     4.91e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.15e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""